### PR TITLE
Gave the ability to customize some of the colors from theme customizer

### PR DESCRIPTION
**Pull request by ericjuden**
Feel free to change if you'd like or not accept it. Thanks for your work on this theme!

### CODE REVIEW

**Comment by braginteractive** [comment]
Thanks for the PR!!

Anyway you could could create a file in the /inc/ directory that hooks into the wp_head to add the custom styles? Something like this: http://code.tutsplus.com/tutorials/adding-the-css-for-a-color-scheme-in-the-theme-customizer--cms-21351

Thoughts?

This will clean up the header.php file.

**Comment by ericjuden** [comment]
Sure, I'll see what I can do.

Eric

**Comment by ericjuden** [comment]
Sorry for the delay. How does this look? I actually just stuck it into the inc/customizer.php file.

**Comment by braginteractive** [comment]
Looks good to me. Thanks!

**Comment by ericjuden** [comment]
No problem! It's a start...

**Pull request merged**
